@host = http://localhost:8787

###
GET {{host}}/api/v1/test
Content-Type: application/json

###
GET {{host}}/api/v1
Content-Type: application/json

###
POST {{host}}/api/v1/auth/register
Content-Type: application/json

{
  "name": "test1111"
}

###
POST {{host}}/api/v1/auth/signin
Content-Type: application/json

{
  "name": "test1111"
}

###
POST {{host}}/api/v1/auth/signout
Content-Type: application/json

###
GET {{host}}/api/v1/questions
Content-Type: application/json

###
GET {{host}}/api/v1/questions/getOrderNum/1
Content-Type: application/json

###
GET {{host}}/api/v1/rooms/95144a33-d37d-0941-2099-882192201c8c
Content-Type: application/json

###
POST {{host}}/api/v1/rooms/95144a33-d37d-0941-2099-882192201c8c/messages
Content-Type: application/json
